# -*- mode: python ; coding: utf-8 -*-

# Stamp this build so the running engine can say what it is.
#
# The engine used to report a hardcoded "0.1.0" and nothing else, so a sidecar
# compiled days earlier looked identical to a fresh one — in the UI and in the
# log. That is how a `UnicodeDecodeError` already fixed in the source went on
# appearing in the field for two days: the code was right, the .exe was old, and
# nothing anywhere said so.
#
# Written to a module PyInstaller then bundles. Regenerated on every build, so
# it cannot go stale relative to the binary it describes.
import datetime as _dt
import subprocess as _sp

def _git():
    try:
        out = _sp.run(["git", "describe", "--always", "--dirty", "--tags"],
                      capture_output=True, text=True, encoding="utf-8",
                      errors="replace", timeout=10)
        return out.stdout.strip() or None if out.returncode == 0 else None
    except Exception:
        return None

with open("_build_info.py", "w", encoding="utf-8") as _fh:
    _fh.write("# Generated by the PyInstaller spec. Do not edit; do not commit.\n")
    _fh.write("BUILT_AT = %r\n" % _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"))
    _fh.write("GIT_DESCRIBE = %r\n" % _git())



from PyInstaller.utils.hooks import collect_data_files as _collect_data_files
from PyInstaller.utils.hooks import copy_metadata as _copy_metadata

# Package metadata, because the report prints these version numbers.
#
# `importlib.metadata.version('scapy')` returns "0.0.0" in a frozen build when
# the distribution's metadata is not bundled — and `capability.probe()` feeds
# that straight into the PDF's method appendix. A report claiming scapy 0.0.0
# names a version that does not exist, in the section whose whole job is letting
# a reader audit what produced the findings.
_METADATA = []
for _dist in ('scapy', 'pywifi', 'pynmea2', 'pyserial', 'numpy', 'scipy', 'scikit-learn'):
    try:
        _METADATA += _copy_metadata(_dist)
    except Exception:
        # A dependency that is not installed is not a build failure; the engine
        # already reports what it could not find.
        pass

# scapy does not read its version from its metadata — it reads a five-byte
# `VERSION` file inside the package. Without it `scapy.__version__` is "0.0.0",
# and that number reached the report's method appendix as a fact.
try:
    _METADATA += _collect_data_files('scapy')
except Exception:
    pass

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=_METADATA,
    hiddenimports=[
        'comtypes', 'pywifi', 'sklearn', 'numpy', 'scipy',
        'scanner.gpr_engine', 'scanner.ssl_check', 'scanner.wps_detect',
        'offensive.hashcat_export', 'offensive.auto_attack',
        # Top-level engine modules. `policy` and `rf` are imported normally and
        # would be found by analysis anyway, but `wordlists_path` is imported
        # lazily inside functions (and inside a try/except in the decryptor),
        # which is exactly the pattern PyInstaller can miss.
        'policy', 'rf', 'wordlists_path',
        'capability', 'logging_setup', 'evidence', 'cve_feed',
        'scanner.evil_twin', 'scanner.clients',
        # The simulator is imported lazily inside _handle_start_scan, and
        # ap_track is only reached through it and through wifi.py — the same
        # lazy-import pattern PyInstaller misses.
        'scanner.simulator', 'scanner.ap_track',
        # net_context is imported inside the IPC handler, the lazy pattern
        # PyInstaller misses; netsh_wlan is reached through both.
        'scanner.netsh_wlan', 'scanner.net_context',
        # The build stamp and the module it reads. `_build_info` is generated
        # above and imported inside a try/except, which analysis cannot see.
        'build_stamp', '_build_info',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

"""
One directory, not one file.

The sidecar used to be built `--onefile`, which appends a 72 MB compressed
archive to the executable and unpacks the whole thing into `%TEMP%\_MEIxxxx`
**on every launch**. Measured on this machine, three runs each: onefile reached
its `ready` event in a median of **20.4 s**; onedir in **2.5 s**. That delay is
what the operator sees as "Engine: OFFLINE" for the first twenty seconds after
opening the app, and it is paid again every single time.

The trade is disk: 162 MB expanded rather than 72 MB compressed. The installer
compresses it back down, and disk is not the resource an operator is short of
while sitting in a car waiting for a scan to start.

Layout: `binaries/ewac-engine/` holds the executable and `_internal/`. The
bootloader resolves `_internal` relative to the executable's own directory, so
the two must stay siblings — `tauri.conf.json` ships `_internal` as a resource
so it lands beside the copied sidecar, and `wordlists/` alongside it for the
same reason. Move one without the other and the engine dies at
`Failed to load Python DLL`.
"""
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ewac-engine-x86_64-pc-windows-msvc',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='ewac-engine',
)
