/**
 * Section 10 of the report: the per-archive detail pages.
 *
 * Moved out of `buildAndSavePDF` verbatim: the body below is the code that was
 * inline, unchanged. The only edits are the values it now takes as parameters
 * instead of reading them from the closure, and `npm run test:export` was run
 * before and after to confirm the document says exactly what it said.
 */
import autoTable from 'jspdf-autotable';
import { apsOf, ascii, credentialsOf, hostsOf, isWirelessReport, summarisePositions } from '../archive';
import { rogueVerdictOf, wpsObserved } from '../../apRisk';
import { AMBIGUOUS_FLAG, apMirror, formatCoord, formatErrorRadius, formatLocationConfidence, formatMetres, isMirrorAmbiguous, locationMethodLabel, locationMethodNote } from '../../position';
import { coordinatePair } from '../../numbers';
import { SEVERITY_ORDER, type Severity } from '../../riskEngine';
import { SEVERITY_RGB } from '../../severityStyle';
import { geometry, TABLE_MARGIN } from '../geometry';
import type { ReportData } from '../assemble';
import type { PdfLayout } from '../layout';

export function renderPerReportDetail(layout: PdfLayout, data: ReportData): void {
  const { doc, tocEntries, paragraph } = layout;
  const { reportsArray, isMixedProvenance, worstFor } = data;
      // --- 10. LOOP THROUGH REPORTS ---
      for (let i = 0; i < reportsArray.length; i++) {
        const r = reportsArray[i];
        const isWifi = isWirelessReport(r);

        // Each target starts its own page: the scope and audit sections now sit
        // between the summary and the telemetry, so there is no summary tail to
        // continue into.
        /*
          Landscape, for the WiFi annexe only.

          Eleven columns of real measurements do not fit 178 mm of portrait page.
          They never did: the columns summed to 202 mm, so the table was drawn to
          216 mm on a 210 mm sheet and the last column — the severity verdict —
          began at 198 mm and landed entirely off the paper. Eleven pages of this
          document carried 372 rectangles outside the printable area, and the
          reader simply never saw the column that says how bad each row is.

          Shrinking to fit would have cost the BSSID column, which already could
          not hold a 17-character MAC at 6.5 pt and was wrapping them mid-address.
          So the annexe turns sideways and the rest of the document does not.
        */
        if (isWifi) doc.addPage('a4', 'landscape'); else doc.addPage();
        const telemetryGeo = geometry(doc);

        tocEntries.push({
          title: `TELEMETRY: ${r.targetName.toUpperCase()}${r.simulated ? ' [SIMULATED]' : ''}`,
          page: (doc as any).internal.getNumberOfPages(),
        });

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text(`TELEMETRY: ${r.targetName.toUpperCase()}`, telemetryGeo.left, 25);

        if (r.simulated) {
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(9);
          doc.setTextColor(161, 98, 7);
          doc.text('SIMULATED OPERATION - the rows below were generated by the hardware simulator and are NOT field-verified.', 14, 31);
        } else if (isMixedProvenance) {
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(9);
          doc.setTextColor(13, 148, 136);
          doc.text('FIELD DATA - captured from live hardware.', 14, 31);
        }

        let head: string[][] = [];
        let body: (string | number)[][] = [];
        /** Which column carries the severity label, for the cell hook below. */
        let severityColumn = 0;
        /** Estimators seen in this operation, so the method can be named once. */
        const methodsSeen = new Set<string>();

        if (isWifi) {
          // Coordinates are the entire point of a wardrive and were absent from
          // every column of this table. So were WPS and the rogue verdict.
          // The coordinate column carries its own uncertainty. A latitude and a
          // longitude with no stated radius is not evidence, and a mirror-ambiguous
          // row is flagged so it cannot be read as a confident fix.
          head = [['BSSID', 'SSID', 'Vendor', 'Security', 'CH/Band', 'RSSI', 'WPS', 'Rogue', 'Latitude, Longitude (95%)', 'Pos. method / flag', 'SEVERITY / CONF.']];
          severityColumn = 10;
          body = apsOf(r).map((ap: any) => {
            const worst = worstFor(ap.bssid);
            const { verdict } = rogueVerdictOf(ap);
            if (ap.location_method) methodsSeen.add(String(ap.location_method));
            const positioned = coordinatePair(ap.latitude, ap.longitude) !== null;
            const ambiguous = positioned && isMirrorAmbiguous(ap);
            const coordCell = positioned
              ? `${formatCoord(ap.latitude, ap.longitude)}\n${formatErrorRadius(ap.location_error_m)}`
              : 'no fix';
            const methodCell = [
              ap.location_method
                ? `${ascii(locationMethodLabel(ap.location_method))} / ${formatLocationConfidence(ap.location_confidence)}`
                : 'not recorded',
              ambiguous
                ? `${AMBIGUOUS_FLAG}\n1 of 2 candidates, ${formatMetres(apMirror(ap)?.distanceM)} apart`
                : '',
            ].filter(Boolean).join('\n');
            return [
              ascii(ap.bssid || 'unknown'),
              ascii(ap.ssid || '<Hidden>'),
              ascii(ap.vendor || 'Unknown'),
              ascii(ap.encryption || 'Unknown'),
              `${ap.channel ?? '-'}${ap.band ? ` / ${ap.band}` : ''}`,
              ap.rssi === undefined || ap.rssi === null ? 'n/r' : `${ap.rssi} dBm`,
              // Spelled out rather than a dash. A dash in a column of measurements
              // reads as "nothing found there", and this report has no legend that
              // would let an abbreviation carry the distinction instead.
              wpsObserved(ap) ? (ap.wps_locked ? 'LOCKED' : 'OPEN PIN') : 'not measured',
              verdict && verdict !== 'CLEAR' ? verdict : '-',
              ascii(coordCell),
              ascii(methodCell),
              `${worst.severity}${worst.confidence ? ` / ${worst.confidence}` : ''}`,
            ];
          });
        } else {
          head = [['IP Address', 'Hostname', 'OS / Signature', 'Open Ports', 'Notes', 'SEVERITY / CONF.']];
          severityColumn = 5;
          const creds = credentialsOf(r);
          body = hostsOf(r).map((h: any) => {
            const ports = (h.open_ports || []).map((p: any) => p.port).join(', ');
            const notes: string[] = [];
            if ((h.snmp_communities || []).length > 0) notes.push('[SNMP EXPOSED]');
            if (creds.some((c: any) => c && String(c.target_ip) === String(h.ip))) notes.push('[CREDENTIALS RECOVERED]');

            const vulnPorts = (h.open_ports || []).filter((p: any) => p.cves && p.cves.length > 0);
            if (vulnPorts.length > 0) {
              notes.push(`[${vulnPorts.reduce((acc: number, p: any) => acc + p.cves.length, 0)} CVE MATCHES]`);
            }
            if (h.isGateway) notes.push('[NETWORK GATEWAY]');

            // Severity from the rule set, not from string-matching this note text.
            const worst = worstFor(h.ip);
            return [
              ascii(h.ip || 'unknown'),
              ascii(h.hostname || 'Unknown'),
              ascii(h.os || 'Unknown'),
              ports,
              notes.join('\n') || '-',
              `${worst.severity}${worst.confidence ? ` / ${worst.confidence}` : ''}`,
            ];
          });
        }

        autoTable(doc, {
          startY: r.simulated || isMixedProvenance ? 37 : 33,
          head: head,
          body: body,
          theme: 'grid',
          headStyles: { fillColor: [30, 41, 59], textColor: 255, fontSize: isWifi ? 6.8 : 9 },
          styles: {
            fontSize: isWifi ? 6.5 : 9,
            cellPadding: isWifi ? 1.5 : 3,
            overflow: 'linebreak',
            textColor: [0, 0, 0],
          },
          columnStyles: isWifi
            ? {
              /*
                265 mm of landscape content column, against 252 mm claimed here.

                The old set summed to 202 mm on a 178 mm portrait page, so the
                rightmost column fell off the sheet. These are sized to what the
                data actually needs: a BSSID is 17 characters of courier, which at
                6.5 pt is about 23.4 mm before padding — the old 24 mm column was
                under a millimetre short and wrapped every address mid-MAC, which
                is where the stray trailing colons came from.
              */
              0: { cellWidth: 30, font: 'courier' },
              1: { cellWidth: 30 },
              2: { cellWidth: 24 },
              3: { cellWidth: 18 },
              4: { cellWidth: 17, halign: 'center' },
              5: { cellWidth: 16, halign: 'center' },
              6: { cellWidth: 16, halign: 'center' },
              7: { cellWidth: 18, halign: 'center' },
              8: { cellWidth: 32, font: 'courier' },
              9: { cellWidth: 32 },
              10: { cellWidth: 19, halign: 'center', fontStyle: 'bold' },
            }
            : { 4: { cellWidth: 44 }, 5: { cellWidth: 30, halign: 'center', fontStyle: 'bold' } },
          margin: TABLE_MARGIN,
          didParseCell: function (data) {
            if (data.section !== 'body') return;
            if (data.column.index === severityColumn) {
              const level = data.cell.text.join(' ').split('/')[0].trim() as Severity;
              if (SEVERITY_RGB[level]) {
                data.cell.styles.textColor = SEVERITY_RGB[level];
                if (SEVERITY_ORDER[level] >= SEVERITY_ORDER.HIGH) data.cell.styles.fontStyle = 'bold';
              }
              return;
            }
            const text = data.cell.text.join('\n');
            // A mirror-ambiguous position must not read like every other row.
            if (isWifi && data.column.index === 9 && text.includes(AMBIGUOUS_FLAG)) {
              data.cell.styles.textColor = [161, 98, 7];
              data.cell.styles.fontStyle = 'bold';
              return;
            }
            if (isWifi && data.column.index === 8 && text.includes('no stated radius')) {
              data.cell.styles.textColor = [161, 98, 7];
              return;
            }
            if (text.includes('OPEN PIN') || text.includes('CREDENTIALS RECOVERED')) {
              data.cell.styles.textColor = [220, 38, 38];
              data.cell.styles.fontStyle = 'bold';
            } else if (/CONFIRMED|LIKELY|SUSPECTED/.test(text) && data.column.index === 7) {
              data.cell.styles.textColor = [217, 119, 6];
              data.cell.styles.fontStyle = 'bold';
            } else if (text.includes('no fix')) {
              data.cell.styles.textColor = [130, 130, 130];
            }
          }
        });

        // One line explaining how the coordinates in this table were arrived at.
        // A latitude and longitude with no method attached invites a reader to
        // treat an RSSI-weighted guess as a surveyed position.
        if (isWifi) {
          let telemetryY = (doc as any).lastAutoTable.finalY + 6;
          const quality = summarisePositions(apsOf(r));
          const positioned = quality.positioned;
          if (quality.ambiguous > 0) {
            telemetryY = paragraph(
              ascii(
                `${quality.ambiguous} row(s) above are flagged ${AMBIGUOUS_FLAG}. For those, the coordinate printed is one of TWO positions that fit the measurements equally well - one on each side of the route - and it must not be read as a fix. Both candidates and their separation are listed in the POSITION QUALITY section of this report.`
              ),
              telemetryY, { size: 8, bold: true, color: [161, 98, 7], lead: 3.6 }
            );
            telemetryY += 2;
          }
          telemetryY = paragraph(
            ascii(
              `POSITIONS: ${positioned} of ${quality.total} access point(s) carry an estimated position. The figure under each coordinate is the radius containing roughly 95% of the posterior for that position; ${quality.radiusMissing} positioned row(s) carry no stated radius, which means the estimator could not produce one and the coordinate cannot be weighed. Every coordinate above is an estimate inferred from received-signal observations taken along the route the operator travelled; none is a surveyed location, and the true radio may sit tens of metres away, typically toward the nearest building. `
              + (methodsSeen.size
                ? Array.from(methodsSeen).map(m => `${locationMethodLabel(m)}: ${locationMethodNote(m)}`).join(' ')
                : 'No estimator was recorded for these positions, so their accuracy characteristics cannot be stated.')
              + ' The percentage beside the method is a display figure derived from that radius, not a probability; the mapping back to metres is given in the method appendix.'
            ),
            telemetryY, { size: 7.5, color: [90, 90, 90], lead: 3.4 }
          );
          if (positioned < quality.total) {
            paragraph(
              'An access point shown as "no fix" was observed without a usable GPS position. It was detected; it simply cannot be placed on a map, so its absence from any map export is a gap in positioning and not in detection.',
              telemetryY, { size: 7.5, color: [161, 98, 7], lead: 3.4 }
            );
          }
        }
      }
}
